src/main/java/at/qe/sepm/skeleton/model/Project.java
package at.qe.sepm.skeleton.model;

import javax.persistence.*;
import java.util.Objects;
import java.util.Set;

/**
 * Entity representing projects.
 */
@Entity
public class Project {

	@Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;
    @Column(unique = true)
    private String name;
    @Column(nullable = true)
    private String description;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "project", cascade = CascadeType.REMOVE)
    private Set<Job> jobs;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "project", cascade = CascadeType.REMOVE)
    private Set<Member> members;

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
    	return description;
    }

    public Set<Job> getJobs() {
    	return jobs;
    }

    public Set<Member> getMembers() {
    	return members;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
    	this.description = description;
    }

    @Override
    public int hashCode() {
        return 413 + Objects.hashCode(name);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof Project))
            return false;

        final Project other = (Project) obj;
        if (!Objects.equals(this.id, other.id))
            return false;

        return true;
    }

    @Override
    public String toString() {
        return name;
    }

}

src/main/java/at/qe/sepm/skeleton/model/User.java
package at.qe.sepm.skeleton.model;

import javax.persistence.*;
import java.util.Objects;
import java.util.Set;
import java.sql.Timestamp;

/**
 * Entity representing users.
 */
@Entity
public class User {

    @Id
    private String username;
    private String firstname;
    private String lastname;
    private String password;
    private String email;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.REMOVE)
    private Set<Member> memberships;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.REMOVE)
    private Set<Time> stamps;
    @ElementCollection(targetClass = UserRole.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "userrole")
    @Enumerated(EnumType.STRING)
    private Set<UserRole> roles;

    public String getUserName() {
        return username;
    }

    public void setUserName(String username) {
        this.username = username;
    }

    public String getFirstName() {
        return firstname;
    }

    public void setFirstName(String firstname) {
        this.firstname = firstname;
    }

    public String getLastName() {
        return lastname;
    }

    public void setLastName(String lastname) {
        this.lastname = lastname;
    }

    public String getPassword() {
        return password;
    }

    public Set<Member> getMemberships() { return memberships; }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set<UserRole> getRoles() {
        return roles;
    }

    public void setRoles(Set<UserRole> roles) {
        this.roles = roles;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.username);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof User)) {
            return false;
        }
        final User other = (User) obj;
        if (!Objects.equals(this.username, other.username)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return username;
        //return username + " (" + firstname + " " + lastname + "), " + password + " [" + roles + "]";
    }

}

src/main/java/at/qe/sepm/skeleton/ui/beans/ProjectMemberBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.*;
import at.qe.sepm.skeleton.services.*;

import java.util.*;

import org.springframework.context.annotation.Scope;
import javax.annotation.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.springframework.beans.factory.annotation.Autowired;

@ManagedBean
@Scope("session")
public class ProjectMemberBean {

	@Autowired
    ProjectService projectService;

    @Autowired
    MemberService memberService;

    @Autowired
    UserService userService;

	private String projectName;
    private Project project;
    private String memberName;
	private User member;
    private String roleName;
	private MemberRole role;

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
        this.project = projectService.getProjectWithName(projectName);
		this.projectName = projectName;
	}

	public String getMemberName() {
		return memberName;
	}

	public void setMemberName(String memberName) {
//System.out.println("set member to: " + memberName);
        this.member = userService.loadUser(memberName);
		this.memberName = memberName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
        role = memberService.getRole(roleName);
		this.roleName = roleName;
	}

    /**
     * Returns a collection of all projects
     */
    public Collection<String> getAllProjectNames() {
        return projectService.getAllProjectNames();
    }

    /**
     * Returns a collection of all possible new members (users, which are not already members of this project)
     */
    public Collection<User> getAllPossibleNewMembers() {
        return projectService.getAllPossibleNewMembers(project);
    }

    /**
     * Returns a collection of all members of the selected project
     */
    public Collection<Member> getAllMembers() {
//System.out.println("members from project: " + project);
        if (project != null)
            return projectService.getMembersOfProject(project);
        else
            return null;
    }

    /**
     * Returns a collection of all possbile roles
     */
    public Collection<MemberRole> getAllRoles() {
        return projectService.getAllRoles();
    }

    public void doAddMemberToProject() {
        Member m = new Member();
        m.setUser(member);
        m.setProject(project);

        Set<UserRole> roles = member.getRoles();
        if (roles.size() > 1) m.setRole(MemberRole.LEADER);
        else m.setRole(MemberRole.STUDENT);

        //user can only be in one project
        FacesContext context = FacesContext.getCurrentInstance();
        if(m.getRole() == MemberRole.LEADER || (member.getMemberships().size() == 0)){
            memberService.save(m);
            context.addMessage("Success", new FacesMessage("The user is now assigned to the project"));
        }
        else {
            context.addMessage("Error", new FacesMessage("This user is already in a project"));
        }

        projectName = "";
        memberName = "";
        roleName = "";
        project = null;
        member = null;
        role = null;
    }

    public void doRemoveMemberFromProject() {
//System.out.println("old member: " + member);
        List<Member> ms = memberService.getMemberByNameInProject(member.getUserName(), project);
        for (Member m : ms)
            memberService.delete(m);
        projectName = "";
        memberName = "";
        project = null;
        member = null;
    }

    public void onProjectUpdate() {
//System.out.println("role: " + roleName + " user: " + member + ", project: " + project);
        getAllPossibleNewMembers();
        getAllMembers();
    }

}

src/main/webapp/admin/csvupload.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:th="http://www.thymeleaf.org"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h4 class="headline">CSV</h4>
        <div class="row">
        <div class="col-md-12">
            <p:panel header="CSV Import" class="stretch" height="100%">
                <div>
                    <form method="POST" enctype="multipart/form-data" action="/files" style="padding: 20px;">
                        <p>Bitte eine CSV mit <a style="color: #00cc66;" href="/resources/files/user-upload-example.csv">folgendem Format</a> uploaden</p>
                        <p>
                            <input type="file" name="file" />
                        </p>
                        <p style="text-align: right;">
                            <input class="button btn btn-success" type="submit" value="Upload" />
                        </p>
                    </form>
                </div>
            </p:panel>

            <h:outputText value="#{FileUpload.message}"
                          style="font-size:40pt; font-family:Roboto Condensed, sans-serif;color: #03BD5B"/><br/>
        </div>
        </div>


    </ui:define>
</ui:composition>

src/main/webapp/admin/projects.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h4 class="headline">Projekte</h4>
        <p:commandButton update=":projectForm:projectCreateDialog" oncomplete="PF('projectCreateDialog').show()" icon="ui-icon-plus" title="New" value="Neues Projekt">
            <!--<f:setPropertyActionListener value="#{project}" target="#{projectDetailController.project}" />-->
        </p:commandButton>
        <p:commandButton update=":projectAddMemberForm:projectAddMemberDialog" oncomplete="PF('projectAddMemberDialog').show()" icon="ui-icon-plus" title="New" value="Mitglied hinzufügen">
            <!--<f:setPropertyActionListener value="" target="" />-->
        </p:commandButton>
        <p:commandButton update=":projectRemoveMemberForm:projectRemoveMemberDialog" oncomplete="PF('projectRemoveMemberDialog').show()" icon="ui-icon-minus" title="Delete" value="Mitglied entfernen">
            <!--<f:setPropertyActionListener value="" target="" />-->
        </p:commandButton>

        <h:form id="projectForm" >
            <p:dataTable id="projectsTable" var="project" value="#{projectListController.projects}">
                <p:column headerText="Projektname" >
                    <h:outputText value="#{project.name}"/>
                </p:column>
                <p:column headerText="Beschreibung">
                    <h:outputText value="#{project.description}"/>
                </p:column>
                <p:column headerText="Mitglieder">
                    <h:outputText value="#{project.members}" />
                </p:column>
                <p:column style="width:100px;text-align: center">
                    <p:commandButton update=":projectForm:projectEditDialog" oncomplete="PF('projectEditDialog').show()" icon="ui-icon-wrench" title="Edit">
                        <f:setPropertyActionListener value="#{project}" target="#{projectDetailController.project}" />
                    </p:commandButton>
                    <p:commandButton action="#{projectDetailController.doDeleteProject}" icon="ui-icon-trash" title="Delete" update=":projectForm:projectsTable">
                        <f:setPropertyActionListener value="#{project}" target="#{projectDetailController.project}" />
                        <p:confirm header="Confirmation" message="Are you sure that you want to delete this project? You cannot undo this operation." icon="ui-icon-alert" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>

            <p:dialog header="Projekt bearbeiten" id="projectEditDialog" widgetVar="projectEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="projectData" rendered="#{not empty projectDetailController.project}">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="name" value="Name: " />
                        <p:inputText id="name" value="#{projectDetailController.project.name}"/>
                        <p:outputLabel for="description" value="Beschr.: " />
                        <p:inputTextarea id="description" rows="10" cols="25" value="#{projectDetailController.project.description}"/>
                    </h:panelGrid>

                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Speichern" action="#{projectDetailController.doSaveProject()}" oncomplete="PF('projectEditDialog').hide()" update=":projectForm:projectsTable"/>
                        <p:commandButton value="Reload" action="#{projectDetailController.doReloadProject()}" update=":projectForm:projectData"/>
                        <p:commandButton value="Abbrechen" onclick="PF('projectEditDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>

            <p:dialog header="Projekt erstellen" id="projectCreateDialog" widgetVar="projectCreateDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="newProjectData">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="newName" value="Name: " />
                        <p:inputText id="newName" value="#{projectCreateController.newProject.name}"/>
                        <p:outputLabel for="newDesc" value="Beschr.: " />
                        <p:inputTextarea id="newDesc" rows="10" cols="25" value="#{projectCreateController.newProject.description}"/>
                    </h:panelGrid>

                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Speichern" action="#{projectCreateController.doSaveProject()}" oncomplete="PF('projectCreateDialog').hide()" update=":projectForm:projectsTable :growl"/>
                        <p:commandButton value="Abbrechen" onclick="PF('projectCreateDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>

            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
                <p:commandButton value="Ja" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                <p:commandButton value="Nein" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
            </p:confirmDialog>
        </h:form>

        <h:form id="projectAddMemberForm">
            <p:dialog header="Mitglied hinzufügen" id="projectAddMemberDialog" widgetVar="projectAddMemberDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="MemberData">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="newMemberProject" value="Projekt: " />
                        <h:selectOneMenu class="menu-dropdown" id="newMemberProject" value="#{projectMemberBean.projectName}">
                            <p:ajax listener="#{projectMemberBean.onProjectUpdate}" update="newMemberProject newMember" />
                            <f:selectItem itemLabel="Projekt ausw." itemValue=""/>
                            <f:selectItems value="#{projectMemberBean.allProjectNames}"/>
                        </h:selectOneMenu>
                        <p:outputLabel for="newMember" value="New Member: " />
                        <h:selectOneMenu class="menu-dropdown" id="newMember" value="#{projectMemberBean.memberName}">
                            <p:ajax listener="#{projectMemberBean.onProjectUpdate}" />
                            <f:selectItem itemLabel="Mitglied ausw." itemValue=""/>
                            <f:selectItems value="#{projectMemberBean.allPossibleNewMembers}"/>
                        </h:selectOneMenu>
                    </h:panelGrid>

                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Speichern" action="#{projectMemberBean.doAddMemberToProject()}" oncomplete="PF('projectAddMemberDialog').hide()" update=":projectForm:projectsTable :growl"/>
                        <p:commandButton value="Abbrechen" onclick="PF('projectAddMemberDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>
        </h:form>

        <h:form id="projectRemoveMemberForm">
            <p:dialog header="Remove Member" id="projectRemoveMemberDialog" widgetVar="projectRemoveMemberDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="RemoveMemberData">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="oldMemberProject" value="Project: " />
                        <h:selectOneMenu class="menu-dropdown" id="oldMemberProject" value="#{projectMemberBean.projectName}">
                            <p:ajax listener="#{projectMemberBean.onProjectUpdate}" update="oldMemberProject oldMember" />
                            <f:selectItem itemLabel="Select Project" itemValue=""/>
                            <f:selectItems value="#{projectMemberBean.allProjectNames}"/>
                        </h:selectOneMenu>
                        <p:outputLabel for="oldMember" value="Old Member: " />
                        <h:selectOneMenu class="menu-dropdown" id="oldMember" value="#{projectMemberBean.memberName}">
                            <p:ajax listener="#{projectMemberBean.onProjectUpdate}" />
                            <f:selectItem itemLabel="Select Member" itemValue=""/>
                            <f:selectItems value="#{projectMemberBean.allMembers}"/>
                        </h:selectOneMenu>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Remove" action="#{projectMemberBean.doRemoveMemberFromProject()}" oncomplete="PF('projectRemoveMemberDialog').hide()" update=":projectForm:projectsTable"/>
                        <p:commandButton value="Abort" onclick="PF('projectRemoveMemberDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/admin/users.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h4 class="headline">Users</h4>
        <p:commandButton update=":userForm:userCreateDialog" oncomplete="PF('userCreateDialog').show()" icon="ui-icon-plus" title="New" value="Neuer User">
            <f:setPropertyActionListener value="#{newUser}" target="#{userCreateController.user}" />
        </p:commandButton>

        <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
            <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check">
                <!-- add delay, to make sure it receives the newest value -->
                <f:ajax delay="50" render=":errorPanel"/>
            </p:commandButton>
            <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close">
            </p:commandButton>
        </p:confirmDialog>

        <h:form id="userForm">
            <p:dataTable id="usersTable" var="user" value="#{userListController.users}">
                <p:column headerText="Username">
                    <h:outputText value="#{user.userName}"/>
                </p:column>
                <p:column headerText="Vorname">
                    <h:outputText value="#{user.firstName}"/>
                </p:column>
                <p:column headerText="Nachname">
                    <h:outputText value="#{user.lastName}"/>
                </p:column>
                <p:column headerText="E-Mail">
                    <h:outputText value="#{user.email}" />
                </p:column>
                <p:column headerText="Rolle">
                    <h:outputText value="#{user.roles}" />
                </p:column>
                <p:column style="width:100px;text-align: center">
                    <p:commandButton update=":userForm:userEditDialog" oncomplete="PF('userEditDialog').show()" icon="ui-icon-wrench" title="Edit">
                        <f:setPropertyActionListener value="#{user}" target="#{userDetailController.user}" />
                    </p:commandButton>
                    <p:commandButton action="#{userDetailController.doDeleteUser}" icon="ui-icon-trash" title="Delete" update=":userForm:usersTable">
                        <f:setPropertyActionListener value="#{user}" target="#{userDetailController.user}" />
                        <p:confirm header="Sicher?" message="Bist du sicher, dass du diesen User löschen möchtest?" icon="ui-icon-alert" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>

            <p:dialog header="User bearbeiten" id="userEditDialog" widgetVar="userEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="userData" rendered="#{not empty userDetailController.user}">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="username" value="Username: " />
                        <p:inputText id="username" value="#{userDetailController.user.userName}" disabled="true"/>
                        <p:outputLabel for="password" value="Passwort: " />
                        <p:password id="password" value="#{userDetailController.user.password}"/>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="2">
                        <p:outputLabel for="firstName" value="Vorname " />
                        <p:inputText id="firstName" value="#{userDetailController.user.firstName}"/>
                        <p:outputLabel for="firstName" value="Nachname: " />
                        <p:inputText id="lastName" value="#{userDetailController.user.lastName}"/>
                        <p:outputLabel for="email" value="E-Mail: " />
                        <p:inputText id="email" value="#{userDetailController.user.email}"/>
                        <p:outputLabel for="roles" value="Rolle: " />
                        <p:selectOneMenu id="roles" value="#{userDetailController.selectedRole}">
                            <f:selectItem itemLabel="Student" itemValue="Student" />
                            <f:selectItem itemLabel="Leiter" itemValue="Leiter" />
                            <f:selectItem itemLabel="Admin" itemValue="Admin" />
                        </p:selectOneMenu>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Speichern" action="#{userDetailController.doSaveUser()}" oncomplete="PF('userEditDialog').hide()" update=":userForm:usersTable"/>
                        <p:commandButton value="Reload" action="#{userDetailController.doReloadUser()}" update=":userForm:userData"/>
                        <p:commandButton value="Abbruch" onclick="PF('userEditDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>


            <p:dialog header="User erstellen" id="userCreateDialog" widgetVar="userCreateDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="newUserData">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="newUsername" value="Username: " />
                        <p:inputText id="newUsername" value="#{userCreateController.newUser.userName}"/>
                        <p:outputLabel for="newPassword" value="Passwort: " />
                        <p:password id="newPassword" value="#{userCreateController.newUser.password}"/>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="2">
                        <p:outputLabel for="newFirstName" value="Vorname: " />
                        <p:inputText id="newFirstName" value="#{userCreateController.newUser.firstName}"/>
                        <p:outputLabel for="newLastName" value="Nachname: " />
                        <p:inputText id="newLastName" value="#{userCreateController.newUser.lastName}"/>
                        <p:outputLabel for="mewEmail" value="E-Mail: " />
                        <p:inputText id="mewEmail" value="#{userCreateController.newUser.email}"/>
                        <p:outputLabel for="newRoles" value="Rolle: " />
                        <p:selectOneMenu id="newRoles" value="#{userCreateController.selectedRole}">
                            <f:selectItem itemLabel="Student" itemValue="Student" />
                            <f:selectItem itemLabel="Leiter" itemValue="Leiter" />
                            <f:selectItem itemLabel="Admin" itemValue="Admin" />
                        </p:selectOneMenu>
                    </h:panelGrid>
                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Speichern" action="#{userCreateController.doSaveNewUser()}" oncomplete="PF('userCreateDialog').hide()" update=":userForm:usersTable"/>
                        <p:commandButton value="Abbrechen" onclick="PF('userCreateDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>

        </h:form>
    </ui:define>
</ui:composition>