src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Session information bean to retrieve session-specific parameters.
 *
 * @author Michael
 *
 */
@Component
@Scope("session")
public class SessionInfoBean {

    @Autowired
    private UserService userService;

    /**
     * Attribute to cache the current user.
     */
    private User currentUser;

    /**
     * Returns the currently logged on user, null if no user is authenticated
     * for this session.
     *
     * @return
     */
    public User getCurrentUser() {
        if (currentUser == null) {
            String currentUserName = getCurrentUserName();
            if (currentUserName.isEmpty()) {
                return null;
            }
            currentUser = userService.loadUser(currentUserName);
        }
        return currentUser;
    }

    public boolean isUserWithoutProject(){
        return userService.getAuthenticatedUser().getMemberships().isEmpty();
    }

    /**
     * Returns the username of the user for this session, empty string if no
     * user has been authenticated for this session.
     *
     * @return
     */
    public String getCurrentUserName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String name = auth.getName(); //get logged in username
        return name;
    }

    public String getCurrentUserRealName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String name = auth.getName(); //get logged in username
        return userService.getUserRealName(name);
    }


    /**
     * Returns the roles of the user for this session as space-separated list,
     * empty string if no user has been authenticated for this session-
     *
     * @return
     */
    public String getCurrentUserRoles() {
        if (!isLoggedIn()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority role : auth.getAuthorities()) {
            sb.append(role.getAuthority());
            sb.append(' ');
        }
        return sb.toString().trim();
    }

    /**
     * Checks if a user is authenticated for this session.
     *
     * @return true if a non-anonymous user has been authenticated, false
     * otherwise
     */
    public boolean isLoggedIn() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
        } else {
            return false;
        }
    }

    /**
     * Checks if the user for this session has the given role (c.f.
     * {@link UserRole}).
     *
     * @param role the role to check for as string
     * @return true if a user is authenticated and the current user has the
     * given role, false otherwise
     */
    public boolean hasRole(String role) {
        if (role == null || role.isEmpty() || !isLoggedIn()) {
            return false;
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority ga : auth.getAuthorities()) {
            if (role.equals(ga.getAuthority())) {
                return true;
            }
        }
        return false;
    }

}

src/main/java/at/qe/sepm/skeleton/ui/beans/StampBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.*;
import at.qe.sepm.skeleton.services.*;

import java.util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;

import javax.annotation.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

/**
 * Created by alexanderleonhartsberger-schr on 12.01.17.
 */
@ManagedBean
@Scope("session")
public class StampBean {

    @Autowired
    private SessionInfoBean sessionInfoBean;

    @Autowired
    private JobService jobService;

    @Autowired
    private TimeService timeService;

    @Autowired
    private UserService userService;

    private String jobstring;
    private Job job;
    private boolean stampDisabled = true;

    public boolean isNoJobs() {
        return noJobs;
    }

    private boolean noJobs = false;

    public Collection<Job> getAllJobs(){
        Set<Member> memberships = userService.getAuthenticatedUser().getMemberships();
        Project userProject = new Project();
        for (Member mbr : memberships){
           userProject = mbr.getProject();
        }
        if (userProject.getJobs().isEmpty()) noJobs = true;
        return userProject.getJobs();
    }

    public void onJobChange(){
    }

    public String getJob() {
        return this.jobstring;
    }


    public void setJob(String job) {

        this.jobstring = job;
        if(job.equals("0")){
            setStampDisabled(true);
        } else {
            this.job = jobService.getJobByName(jobstring);
            setStampDisabled(false);
        }
    }

    public void setStampDisabled (boolean value) {
        this.stampDisabled = value;
    }

    public boolean getStampDisabled(){
        return stampDisabled;
    }


    public String getCurrentUserRealName(){
        return sessionInfoBean.getCurrentUserRealName();
    }

    public boolean isStamped(){
        return timeService.isStampedIn();
    }

    public String getButtonText() {
        if(isStamped()) return "Ausstempeln";
        else return "Einstempeln";
    }

    public void stamp() {

        boolean oldValue = isStamped();
        timeService.stamp(job);
        FacesContext context = FacesContext.getCurrentInstance();
        if (oldValue != isStamped()) context.addMessage("Eingestempelt", new FacesMessage("Stempelvorgang erfolgreich"));
        else System.out.println("not stamped");
    }

}

src/main/java/at/qe/sepm/skeleton/ui/beans/StudentTimeBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.Time;
import at.qe.sepm.skeleton.model.Job;
import at.qe.sepm.skeleton.services.TimeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.Collection;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Created by alexanderleonhartsberger-schr on 13.01.17.
 */
@Component
@Scope("request")
public class StudentTimeBean {

    @Autowired
    TimeService timeService;

    public Collection<Time> getAllTimes(){
        return timeService.getTimes();
    }

    public String getTotalTime(){
        Collection<Time> times = getAllTimes();
        long totalTime = 0;
        for (Time oneTime : times) {
            if (oneTime.getToTime() != null ) {
                long interval = oneTime.getToTime().getTime() - oneTime.getFromTime().getTime();
                totalTime += interval;
            }
        }
        String hms = String.format("%02d:%02d:%02d", TimeUnit.MILLISECONDS.toHours(totalTime),
                TimeUnit.MILLISECONDS.toMinutes(totalTime) - TimeUnit.HOURS.toMinutes(TimeUnit.MILLISECONDS.toHours(totalTime)),
                TimeUnit.MILLISECONDS.toSeconds(totalTime) - TimeUnit.MINUTES.toSeconds(TimeUnit.MILLISECONDS.toMinutes(totalTime)));
        return hms;
    }

    public class TimesListItem {

        private String date;
        private String duration;
        private String job = "<none>";

        public String getDuration() {
            return duration;
        }

        public String getDate() {
            return date;
        }

        public String getJob() {
            return job;
        }

    }

    public List getTimesList(){
//System.out.println("this is called");
        Collection<Time> times = getAllTimes();
        List<TimesListItem> list = new LinkedList<TimesListItem>();
        for (Time oneTime : times) {
            if (oneTime.getToTime() != null ) {
                String fromDate = oneTime.getFromTime().toString().substring(0,11);
                long duration = (oneTime.getToTime().getTime() - oneTime.getFromTime().getTime()) / 1000;
                long h = duration / 3600;
                long m = (duration - h * 3600) / 60;
                long s = duration - h * 3600 - m * 60;
                TimesListItem item = new TimesListItem();
                item.date = fromDate;
                item.duration = String.format("%02d", h) + ":" + String.format("%02d", m) + ":" + String.format("%02d", s);
                item.job = oneTime.getJob().getName();
                list.add(item);
            }
        }
        return list;
    }

}

src/main/webapp/secured/includes/dash-admin.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">
    <div class="row">
        <div class="col-md-12">
            <p:panel class="stats-splash">
                <div class="text-center primary-panel-font">
                    <i class="fa fa-cog"/><br/>Willkommen im Admin panel. Bitte Menüpunkt auswählen
                </div>
            </p:panel>
        </div>
    </div>
</ui:composition>

src/main/webapp/secured/includes/dash-manage.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">
    <h:panelGroup rendered="#{!sessionInfoBean.userWithoutProject}">
    <a href="/manager/stats.xhtml">
        <div class="row">
            <div class="col-md-12">
                <p:panel class="stats-splash">
                    <div class="text-center primary-panel-font">
                        <i class="fa fa-line-chart"/><br/>Zu den Statistiken
                    </div>
                </p:panel>
            </div>
        </div>
    </a>
    </h:panelGroup>
    <h:panelGroup rendered="#{sessionInfoBean.userWithoutProject}">
        <p:panel class="stats-splash">
            <div class="text-center primary-panel-font">
                <i class="fa fa-warning"/><br/>Du bist keinem Projekt zugeteilt. Ein Fall für den Admin
            </div>
        </p:panel>
    </h:panelGroup>
</ui:composition>

src/main/webapp/secured/includes/dash-student.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui"
        xmlns:pt="http://java.sun.com/jsf/composite">
    <h:panelGroup rendered="#{!sessionInfoBean.userWithoutProject}">
    <div class="row row-eq-height">

        <!-- Stamp Card -->
        <div class="col-md-6">
            <p:panel class="default-size"
                     styleClass="#{stampBean.stamped ? 'primary-panel-logged-in' : 'primary-panel-logged-out'}">
                <div class="primary-panel-font">
                    <h:outputLabel style="font-size: 30pt;" rendered="#{stampBean.stamped}"><i
                            class="fa fa-thumbs-up"/></h:outputLabel>
                    <h:outputLabel style="font-size: 30pt;" rendered="#{!stampBean.stamped}"><i
                            class="fa fa-thumbs-down"/></h:outputLabel><br/>
                    <h:outputText style="font-size: 20pt;text-transform: uppercase"
                                  value="#{stampBean.currentUserRealName}"/><br/>
                    <h:outputText
                            style="font-size: 10pt;text-transform: uppercase; font-family: Roboto Condensed, sans-serif;"
                            value="Hart bei der Arbeit" rendered="#{stampBean.stamped}"/>
                    <h:outputText
                            style="font-size: 10pt;text-transform: uppercase; font-family: Roboto Condensed, sans-serif;"
                            value="Nicht bei der Arbeit" rendered="#{!stampBean.stamped}"/><br/>
                    <div style="padding-top: 10px;overflow:hidden">
                        <h:form id="stamp-card" action="secured/dash.xhtml">
                        <h:selectOneMenu class="menu-dropdown" id="job" value="#{stampBean.job}" disabled="#{stampBean.noJobs}"
                                         rendered="#{!stampBean.stamped}">
                            <p:ajax listener="#{stampBean.onJobChange}" update="stamp-card"/>
                            <f:selectItem itemLabel="Job auswählen" itemValue="0"/>
                            <f:selectItems value="#{stampBean.allJobs}"/>
                        </h:selectOneMenu>
                            <h:commandButton title="Job auswählen und Stempeln. Kein Job = kein Stempeln" value="#{stampBean.buttonText}" actionListener="#{stampBean.stamp}" rendered="#{!stampBean.stamped}" disabled="#{stampBean.stampDisabled}"
                                             styleClass="stamp-button" update=":growl" />
                            <h:commandButton title="Job auswählen und Stempeln. Kein Job = kein Stempeln" value="#{stampBean.buttonText}" actionListener="#{stampBean.stamp}" rendered="#{stampBean.stamped}"
                                             styleClass="stamp-button" update=":growl" />
                        </h:form>
                    </div>
                </div>
            </p:panel></div>


        <!-- Total time Card -->
        <div class="col-md-6"><p:panel header="Deine Gesamtzeit" class="stretch" height="100%">
            <br/>
            <div class="text-center">
                <h:outputText value="#{studentTimeBean.totalTime}"
                              style="font-size:40pt; font-family:Roboto Condensed, sans-serif;color: #03BD5B"/><br/>
                <h:outputText value="seit Beginn des Projekts"
                              style="font-family: Roboto Condensed, sans-serif; font-size: 15px;"></h:outputText>
            </div>
        </p:panel></div>
    </div>
    <div class="row">
        <div class="col-md-12">
        <p:panel header="Deine Zeiten" class="stretch" height="100%">
            <p:dataTable id="timessTable" var="time" type="ordered" value="#{studentTimeBean.timesList}">
                <p:column headerText="Datum" >
                    <h:outputText value="#{time.date}"/>
                </p:column>
                <p:column headerText="Job" >
                    <h:outputText value="#{time.job}"/>
                </p:column>
                <p:column headerText="Dauer" >
                    <h:outputText value="#{time.duration}"/>
                </p:column>
            </p:dataTable>
        </p:panel>
        </div>
    </div>
    </h:panelGroup>
    <h:panelGroup rendered="#{sessionInfoBean.userWithoutProject}">
        <p:panel class="stats-splash">
            <div class="text-center primary-panel-font">
                <i class="fa fa-warning"/><br/>Du bist keinem Projekt zugeteilt. Ein Fall für den Admin
            </div>
        </p:panel>
    </h:panelGroup>
</ui:composition>