src/main/java/at/qe/sepm/skeleton/model/Job.java
package at.qe.sepm.skeleton.model;

import javax.persistence.*;
import java.util.Objects;
import java.util.Set;

/**
 * Entity representing jobs.
 */
@Entity
public class Job {

	@Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;
    @Column(unique = true)
    private String name;
    @Column(nullable = true)
    private String description;
    @ManyToOne
    @JoinColumn(name = "projectid")
    private Project project;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "job", cascade = CascadeType.REMOVE)
    private Set<Time> stamps;

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
    	return description;
    }

    public Project getProject() {
        return project;
    }

    public Set<Time> getStamps() {
        return stamps;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
    	this.description = description;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @Override
    public int hashCode() {
        return 413 + Objects.hashCode(name);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof Job))
            return false;

        final Job other = (Job) obj;
        if (!Objects.equals(this.id, other.id))
            return false;

        return true;
    }

    @Override
    public String toString() {
        return name;
    }

}

src/main/java/at/qe/sepm/skeleton/model/User.java
package at.qe.sepm.skeleton.model;

import javax.persistence.*;
import java.util.Objects;
import java.util.Set;
import java.sql.Timestamp;

/**
 * Entity representing users.
 */
@Entity
public class User {

    @Id
    private String username;
    private String firstname;
    private String lastname;
    private String password;
    private String email;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.REMOVE)
    private Set<Member> memberships;
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.REMOVE)
    private Set<Time> stamps;
    @ElementCollection(targetClass = UserRole.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "userrole")
    @Enumerated(EnumType.STRING)
    private Set<UserRole> roles;

    public String getUserName() {
        return username;
    }

    public void setUserName(String username) {
        this.username = username;
    }

    public String getFirstName() {
        return firstname;
    }

    public void setFirstName(String firstname) {
        this.firstname = firstname;
    }

    public String getLastName() {
        return lastname;
    }

    public void setLastName(String lastname) {
        this.lastname = lastname;
    }

    public String getPassword() {
        return password;
    }

    public Set<Member> getMemberships() { return memberships; }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set<UserRole> getRoles() {
        return roles;
    }

    public void setRoles(Set<UserRole> roles) {
        this.roles = roles;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 59 * hash + Objects.hashCode(this.username);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof User)) {
            return false;
        }
        final User other = (User) obj;
        if (!Objects.equals(this.username, other.username)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return username;
        //return username + " (" + firstname + " " + lastname + "), " + password + " [" + roles + "]";
    }

}

src/main/java/at/qe/sepm/skeleton/ui/beans/StampBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.*;
import at.qe.sepm.skeleton.services.*;

import java.util.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;

import javax.annotation.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

/**
 * Created by alexanderleonhartsberger-schr on 12.01.17.
 */
@ManagedBean
@Scope("session")
public class StampBean {

    @Autowired
    private SessionInfoBean sessionInfoBean;

    @Autowired
    private JobService jobService;

    @Autowired
    private TimeService timeService;

    @Autowired
    private UserService userService;

    private String jobstring;
    private Job job;
    private boolean stampDisabled = true;

    public boolean isNoJobs() {
        return noJobs;
    }

    private boolean noJobs = false;

    public Collection<Job> getAllJobs(){
        Set<Member> memberships = userService.getAuthenticatedUser().getMemberships();
        Project userProject = new Project();
        for (Member mbr : memberships){
           userProject = mbr.getProject();
        }
        if (userProject.getJobs().isEmpty()) noJobs = true;
        return userProject.getJobs();
    }

    public void onJobChange(){
    }

    public String getJob() {
        return this.jobstring;
    }


    public void setJob(String job) {

        this.jobstring = job;
        if(job.equals("0")){
            setStampDisabled(true);
        } else {
            this.job = jobService.getJobByName(jobstring);
            setStampDisabled(false);
        }
    }

    public void setStampDisabled (boolean value) {
        this.stampDisabled = value;
    }

    public boolean getStampDisabled(){
        return stampDisabled;
    }


    public String getCurrentUserRealName(){
        return sessionInfoBean.getCurrentUserRealName();
    }

    public boolean isStamped(){
        return timeService.isStampedIn();
    }

    public String getButtonText() {
        if(isStamped()) return "Ausstempeln";
        else return "Einstempeln";
    }

    public void stamp() {

        boolean oldValue = isStamped();
        timeService.stamp(job);
        FacesContext context = FacesContext.getCurrentInstance();
        if (oldValue != isStamped()) context.addMessage("Eingestempelt", new FacesMessage("Stempelvorgang erfolgreich"));
        else System.out.println("not stamped");
    }

}

src/main/java/at/qe/sepm/skeleton/ui/beans/StatsBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.Project;
import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.services.ProjectService;
import at.qe.sepm.skeleton.services.UserService;
import at.qe.sepm.skeleton.ui.controllers.StatisticsController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;

import javax.annotation.ManagedBean;
import javax.faces.bean.ViewScoped;
import java.util.Collection;

/**
 * Created by alexander on 15.01.17.
 */
@ManagedBean
@Scope("session")
public class StatsBean {

    @Autowired
    ProjectService projectService;
    @Autowired
    UserService userService;
    StatisticsController statisticsController;
    @Autowired
    public StatsBean(StatisticsController statisticsController){
        this.statisticsController=statisticsController;
    }
    @Autowired
    private SessionInfoBean sessionInfo;

    private String project;
    private String student;

    public Collection<Project> getAllProjects(){
        return projectService.getAllProjects();
    }
    
    public Collection<Project> getProjectsOfLeader(){
        return projectService.getProjectsOfLeader(sessionInfo.getCurrentUserName());
    }

    public Collection<User> getCorrespondingStudents(){
            return userService.getAllUsersFromProject(project);
    }


    public String getProject() {
        return this.project;
    }

    public void setProject(String project) {
        this.project = project;
    }

    public String getStudent(){
        return this.student;
    }

    public void setStudent(String student){
        this.student = student;
    }

    public void onProjectChange(){
        userService.getAllUsersFromProject(project);
    }

    public void onStudentChange(){
        statisticsController.setSelection(projectService.getProjectWithName(project).getId() +","+student);
        statisticsController.buttonAction();
    }

}

src/main/java/at/qe/sepm/skeleton/ui/controllers/JobCreateController.java
package at.qe.sepm.skeleton.ui.controllers;

import at.qe.sepm.skeleton.model.Job;
import at.qe.sepm.skeleton.model.Project;
import at.qe.sepm.skeleton.services.JobService;
import at.qe.sepm.skeleton.services.ProjectService;
import at.qe.sepm.skeleton.ui.beans.SessionInfoBean;

import java.util.Collection;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Controller for the job detail view.
 *
 * @author Stephan Eberharter <stephan.eberharter@student.uibk.ac.at>
 * @version 1.0
 */
@Component
@Scope("view")
public class JobCreateController {

    @Autowired
    private JobService jobService;
    @Autowired
    private ProjectService projectService;
    @Autowired
    private SessionInfoBean sessionInfo;

    private Job newJob;
    private String project;
    
    public Collection<Project> getPossibleProjects(){
    	if(sessionInfo.hasRole(at.qe.sepm.skeleton.model.UserRole.ADMIN.toString())) {
    		return projectService.getAllProjects();
    	} else {
    		return projectService.getProjectsOfLeader(sessionInfo.getCurrentUserName());
    	}
    }

    public void setNewJob(Job newJob) {
        this.newJob = newJob;
        doReloadNewJob();
    }

    /**
     * Returns the currently displayed job.
     *
     * @return
     */
    public Job getNewJob() {
        if(newJob != null) return newJob;
        else {
            newJob = new Job();
            newJob.setName("Job Name");
            return newJob;
        }
    }

    /**
     * Action to force a reload of the currently displayed job.
     */
    public void doReloadNewJob() {
        newJob = jobService.loadJob(newJob.getId());
    }

    /**
     * Action to save the currently displayed job.
     */
    public void doSaveJob() {
        newJob = this.jobService.saveJob(newJob);
    }

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		newJob.setProject(projectService.getProjectWithName(project));
		this.project = project;
	}

}

src/main/webapp/manager/jobs.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                template="/WEB-INF/templates/main.xhtml">
    <ui:define name ="content">
        <h4 class="headline">Jobs</h4>
        <p:commandButton update=":jobForm:jobCreateDialog" oncomplete="PF('jobCreateDialog').show()" icon="ui-icon-plus" title="New" value="New Job">
            <f:setPropertyActionListener value="#{job}" target="#{jobDetailController.job}" />
        </p:commandButton>

        <h:form id="jobForm">
            <p:dataTable id="jobsTable" var="job" value="#{jobListController.jobs}">
                <p:column headerText="Name">
                    <h:outputText value="#{job.name}"/>
                </p:column>
                <p:column headerText="Beschreibung">
                    <h:outputText value="#{job.description}"/>
                </p:column>
                <p:column headerText="Projekt">
                    <h:outputText value="#{job.project}"/>
                </p:column>
                <p:column style="width:100px;text-align: center">
                    <p:commandButton update=":jobForm:jobEditDialog" oncomplete="PF('jobEditDialog').show()" icon="ui-icon-wrench" title="Edit">
                        <f:setPropertyActionListener value="#{job}" target="#{jobDetailController.job}" />
                    </p:commandButton>
                    <p:commandButton action="#{jobDetailController.doDeleteJob}" icon="ui-icon-trash" title="Delete" update=":jobForm:jobsTable">
                        <f:setPropertyActionListener value="#{job}" target="#{jobDetailController.job}" />
                        <p:confirm header="Confirmation" message="Are you sure that you want to delete this job? You cannot undo this operation." icon="ui-icon-alert" />
                    </p:commandButton>
                </p:column>
            </p:dataTable>

            <p:dialog header="Job bearbeiten" id="jobEditDialog" widgetVar="jobEditDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="jobData" rendered="#{not empty jobDetailController.job}">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="name" value="Name: " />
                        <p:inputText id="name" value="#{jobDetailController.job.name}"/>
                        <p:outputLabel for="description" value="Beschr.: " />
                        <p:inputTextarea id="description" rows="10" cols="25" value="#{jobDetailController.job.description}"/>
                        
                        <p:outputLabel for="editProject" value="Project: " />
                        <h:selectOneMenu class="menu-dropdown" id="editProject" value="#{jobDetailController.project}">
                        	<f:selectItem itemLabel="Projekt ausw." itemValue="" noSelectionOption="true" />
                        	<f:selectItems value="#{jobDetailController.possibleProjects}" />
                    	</h:selectOneMenu>  
                    </h:panelGrid>

                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Speichern" action="#{jobDetailController.doSaveJob()}" oncomplete="PF('jobEditDialog').hide()" update=":jobForm:jobsTable"/>
                        <p:commandButton value="Reload" action="#{jobDetailController.doReloadJob()}" update=":jobForm:jobData"/>
                        <p:commandButton value="Abbrechen" onclick="PF('jobEditDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>

            <p:dialog header="Job erstellen" id="jobCreateDialog" widgetVar="jobCreateDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="newJobData">
                    <h:panelGrid columns="2">
                        <p:outputLabel for="newName" value="Name: " />
                        <p:inputText id="newName" value="#{jobCreateController.newJob.name}"/>
                        <p:outputLabel for="newDesc" value="Beschreibung: " />
                        <p:inputTextarea id="newDesc" rows="10" cols="25" value="#{jobCreateController.newJob.description}"/>
                        
                        <p:outputLabel for="newProject" value="Project: " />
                        <h:selectOneMenu class="menu-dropdown" id="newProject" value="#{jobCreateController.project}">
                        	<f:selectItem itemLabel="Select Project" itemValue="" noSelectionOption="true" />
                        	<f:selectItems value="#{jobCreateController.possibleProjects}" />
                    	</h:selectOneMenu>                      
                    </h:panelGrid>

                    <p:separator />
                    <h:panelGrid columns="3">
                        <p:commandButton value="Save" action="#{jobCreateController.doSaveJob()}" oncomplete="PF('jobCreateDialog').hide()" update=":jobForm:jobsTable"/>
                        <p:commandButton value="Abort" onclick="PF('jobCreateDialog').hide()"/>
                    </h:panelGrid>
                </p:outputPanel>
            </p:dialog>

            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade" width="300">
                <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
            </p:confirmDialog>

        </h:form>
    </ui:define>
</ui:composition>

src/main/webapp/manager/stats.xhtml
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui"
        template="/WEB-INF/templates/main.xhtml">
    <ui:define name="content">
        <h4 class="headline">Statistiken</h4>
        <h:panelGroup rendered="#{sessionInfoBean.hasRole('MANAGER') and !sessionInfoBean.hasRole('ADMIN')}">
            <h:form>
                <div class="row">
                    <div class="col-md-6 col-sm-12 menubar">
                        <div id="header-name">#{sessionInfoBean.currentUserRealName}</div>
                    </div>

                    <div class="col-md-3 col-sm-6">
                        <h:selectOneMenu class="menu-dropdown" id="project" value="#{statsBean.project}">
                            <p:ajax listener="#{statsBean.onProjectChange}" update="user stats"/>
                            <f:selectItem itemLabel="Select Team" noSelectionOption="true"></f:selectItem>
                            <f:selectItems value="#{statsBean.projectsOfLeader}"/>
                        </h:selectOneMenu>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <h:selectOneMenu id="user" class="menu-dropdown" value="#{statsBean.student}">
                            <p:ajax listener="#{statsBean.onStudentChange}" update="user stats"/>
                            <f:selectItem itemLabel="Select User" noSelectionOption="true"></f:selectItem>
                            <f:selectItems value="#{statsBean.correspondingStudents}" var="member" itemValue="#{member}" itemLabel="#{member.firstName} #{member.lastName}"/>
                        </h:selectOneMenu>
                    </div>

                </div>
            </h:form>
        </h:panelGroup>
        <h:panelGroup id="stats" rendered="#{sessionInfoBean.hasRole('MANAGER') and !sessionInfoBean.hasRole('ADMIN')}">
            <h:panelGroup rendered="#{!statisticsController.showCharts}">
                <div class="row">
                    <div class="col-md-12">
                        <p:panel class="stats-splash">
                            <div class="row text-center primary-panel-font">
                                <div class="col-md-4"><i class="fa fa-users"/><br/>Team auswählen</div>
                                <div class="col-md-4"><i class="fa fa-user"/><br/>Nutzer auswählen</div>
                                <div class="col-md-4"><i class="fa fa-line-chart"/><br/>Enjoy</div>
                            </div>
                        </p:panel>
                    </div>
                </div>
            </h:panelGroup>
            <h:panelGroup rendered="#{statisticsController.showCharts}">
                <div class="row">
                    <div class="col-md-12">
                        <p:panel style="height:50px;"><h:form id="form">
                            <h:panelGroup style="float: right; flex: auto; color: #03BD5B"><i
                                    class="fa fa-hourglass-start"/>&#160;&#160;
                                <p:calendar id="popup" value="#{statisticsController.from}"/>&#160;&#160;

                                <i class="fa fa-hourglass-end" style="color: #D1335B"/>&#160;&#160;
                                <p:calendar id="popup2" value="#{statisticsController.to}"/>&#160;&#160;
                                <p:commandButton value="Submit" icon="ui-icon-check" id="nonAjax"
                                                 actionListener="#{statisticsController.buttonAction}" ajax="false"/>
                            </h:panelGroup>
                        </h:form>
                        </p:panel>
                    </div>
                </div>
                <div class="row row-eq-height">

                    <div class="col-md-12 col-lg-6">
                        <p:panel header="Arbeitsstunden - #{statsBean.student}" class="stretch" height="100%">
                            <p:chart type="bar" model="#{statisticsController.barModel}"
                                     style="height:300; width: 400;"/>
                        </p:panel>
                    </div>

                    <div class="col-md-12 col-lg-6"><p:panel styleClass="text-center"
                                                             header="Woran hat #{statsBean.student} gearbeitet?"
                                                             class="stretch" height="100%">
                        <p:chart type="pie" model="#{statisticsController.pieModel1}" style="width:400px;height:300px"/>
                    </p:panel></div>

                    <div class="col-md-12 col-lg-6">
                        <p:panel header="Arbeitsteilung - #{statsBean.project}" class="stretch" height="100%">
                            <p:chart type="pie" model="#{statisticsController.pieModel3}"
                                     style="height:300px; width: 400px;"/>
                        </p:panel>
                    </div>


                    <div class="col-md-12 col-lg-6"><p:panel header="Verglichen mit seinem Team?" class="stretch"
                                                             height="100%">
                        <p:chart type="pie" model="#{statisticsController.pieModel2}" style="width:400px;height:300px"/>
                    </p:panel></div>


                </div>

            </h:panelGroup>
        </h:panelGroup>
    </ui:define>
</ui:composition>