src/main/java/at/qe/sepm/skeleton/ui/beans/SessionInfoBean.java
package at.qe.sepm.skeleton.ui.beans;

import at.qe.sepm.skeleton.model.User;
import at.qe.sepm.skeleton.model.UserRole;
import at.qe.sepm.skeleton.services.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;

/**
 * Session information bean to retrieve session-specific parameters.
 *
 * @author Michael
 *
 */
@Component
@Scope("session")
public class SessionInfoBean {

    @Autowired
    private UserService userService;

    /**
     * Attribute to cache the current user.
     */
    private User currentUser;

    /**
     * Returns the currently logged on user, null if no user is authenticated
     * for this session.
     *
     * @return
     */
    public User getCurrentUser() {
        if (currentUser == null) {
            String currentUserName = getCurrentUserName();
            if (currentUserName.isEmpty()) {
                return null;
            }
            currentUser = userService.loadUser(currentUserName);
        }
        return currentUser;
    }

    public boolean isUserWithoutProject(){
        return userService.getAuthenticatedUser().getMemberships().isEmpty();
    }

    /**
     * Returns the username of the user for this session, empty string if no
     * user has been authenticated for this session.
     *
     * @return
     */
    public String getCurrentUserName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String name = auth.getName(); //get logged in username
        return name;
    }

    public String getCurrentUserRealName() {
        if (!isLoggedIn()) {
            return "";
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        String name = auth.getName(); //get logged in username
        return userService.getUserRealName(name);
    }


    /**
     * Returns the roles of the user for this session as space-separated list,
     * empty string if no user has been authenticated for this session-
     *
     * @return
     */
    public String getCurrentUserRoles() {
        if (!isLoggedIn()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority role : auth.getAuthorities()) {
            sb.append(role.getAuthority());
            sb.append(' ');
        }
        return sb.toString().trim();
    }

    /**
     * Checks if a user is authenticated for this session.
     *
     * @return true if a non-anonymous user has been authenticated, false
     * otherwise
     */
    public boolean isLoggedIn() {
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        if (auth != null) {
            return auth.isAuthenticated() && !auth.getName().equals("anonymousUser");
        } else {
            return false;
        }
    }

    /**
     * Checks if the user for this session has the given role (c.f.
     * {@link UserRole}).
     *
     * @param role the role to check for as string
     * @return true if a user is authenticated and the current user has the
     * given role, false otherwise
     */
    public boolean hasRole(String role) {
        if (role == null || role.isEmpty() || !isLoggedIn()) {
            return false;
        }
        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        for (GrantedAuthority ga : auth.getAuthorities()) {
            if (role.equals(ga.getAuthority())) {
                return true;
            }
        }
        return false;
    }

}

src/main/webapp/WEB-INF/includes/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://xmlns.jcp.org/jsf/core">
<body>
<ui:composition>
    <p:growl id="growl" sticky="true"></p:growl>
    <!--Render the whole top Menu only when logged in -->
    <h:panelGroup rendered="#{sessionInfoBean.loggedIn}">
        <div class="row" id="header">
            <!-- Start of the logo/logout header-->
            <div class="col-md-6 col-6">
                <a href="/secured/dash.xhtml"><img src="../../resources/img/logo.png" height="40" alt="logo"/></a>
            </div>
            <div class="col-md-6 col-6 text-right" id="logout-col">
                <h:form action="/logout">
                    <a href="/logout" id="logout">Log out</a>
                </h:form>

            </div>
            <!--End of Logo/Logout header-->
        </div>
        <!-- Start of New Menu-->
        <h:panelGroup rendered="#{sessionInfoBean.hasRole('ADMIN')}">
            <div class="row row-eq-height">
            <div class="col-md-3 col-6"><a href="/admin/users.xhtml"><p:panel class="stretch" height="100%"
                                           styleClass="adminPanelElement">

                    <i class="fa fa-user menu-panel-font"></i>
                    <h6 class="menu-panel-font">Benutzer</h6>

            </p:panel></a></div>

            <div class="col-md-3 col-6"><a href="/admin/projects.xhtml"><p:panel class="stretch" height="100%"
                                           styleClass="adminPanelElement">

                    <i class="fa fa-book menu-panel-font"></i>
                    <h6 class="menu-panel-font">Projekte</h6>

            </p:panel></a></div>
            <div class="col-md-3 col-6"><a href="/manager/jobs.xhtml"><p:panel class="stretch" height="100%"
                                           styleClass="adminPanelElement">

                    <i class="fa fa-suitcase menu-panel-font"></i>
                    <h6 class="menu-panel-font">Arbeitspakete</h6>

            </p:panel></a></div>
            <div class="col-md-3 col-6"><a href="/admin/csvupload.xhtml"><p:panel class="stretch" height="100%"
                                           styleClass="adminPanelElement">

                    <i class="fa fa-upload menu-panel-font"></i>
                    <h6 class="menu-panel-font">CSV Upload</h6>

            </p:panel></a></div>
            </div>
        </h:panelGroup>

        <h:panelGroup rendered="#{sessionInfoBean.hasRole('MANAGER') and !sessionInfoBean.hasRole('ADMIN')}">
            <div class="row row-eq-height">
                <div class="col-md-6 col-6"><a href="/manager/jobs.xhtml"><p:panel class="stretch" height="100%"
                                                                                   styleClass="adminPanelElement">
                    <i class="fa fa-suitcase menu-panel-font"></i>
                    <h6 class="menu-panel-font">Jobs bearbeiten</h6>
                </p:panel></a></div>
                <div class="col-md-6 col-6"><a href="/manager/stats.xhtml"><p:panel class="stretch" height="100%"
                                                                                     styleClass="adminPanelElement">
                    <i class="fa fa-suitcase menu-panel-font"></i>
                    <h6 class="menu-panel-font">Statistiken</h6>
                </p:panel></a></div>
            </div>
        </h:panelGroup>

    </h:panelGroup>
</ui:composition>
</body>
</html>